# Generated by Django 2.0.6 on 2018-06-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180614_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='none', max_length=20, verbose_name='住所'),
        ),
    ]
